# Generated by Django 4.2 on 2023-07-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0002_alter_flight_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
