# Generated by Django 4.2 on 2023-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0003_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
