# Generated by Django 4.2 on 2023-08-28 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights_app', '0005_flight_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_passes', to='flights_app.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boarding_passes',
            },
        ),
    ]
